### ISSUE TITLE
createBackup failed: wrong method name

### ISSUE THREAD

**Issue by wylbjia** [vesoft-inc/nebula-br#5]
do  as the doc says

```
./br backup full --config "/root/nebula-br/config/backup_example.yaml"
```
my yaml file 

```
root@host:~/nebula-br/config# cat backup_example.yaml 
meta_nodes:
  - addrs: "10.90.71.12:45500"
    root: "/usr/local/nebula/"
    data: "/usr/local/nebula/data/meta"
    user: "nebula"

storage_nodes:
  - addrs: "10.90.71.12:44500"
    root: "/usr/local/nebula/"
    data: "/usr/local/nebula/data/storage"
    user: "nebula"

max_ssh_connections: 10
backend: "local:///home/jiakunpeng/backup/"
space_names: ["test"]
```
come up with that error 
```
{"level":"error","ts":1618560054.9361813,"caller":"backup/backup.go:196","msg":"backup cluster failed","error":"createBackup failed: wrong method name","stacktrace":"github.com/vesoft-inc/nebula-br/pkg/backup.(*Backup).BackupCluster\n\t/root/nebula-br/pkg/backup/backup.go:196\ngithub.com/vesoft-inc/nebula-br/cmd.newFullBackupCmd.func2\n\t/root/nebula-br/cmd/backup.go:86\ngithub.com/spf13/cobra.(*Command).execute\n\t/root/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/root/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958\ngithub.com/spf13/cobra.(*Command).Execute\n\t/root/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895\nmain.main\n\t/root/nebula-br/main.go:15\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"}
Error: createBackup failed: wrong method name
```

anybody help @Shylock-Hg
